# Generated by Django 5.1.1 on 2024-09-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resume/media/profile_photo/')),
            ],
        ),
        migrations.AlterField(
            model_name='about_img',
            name='image',
            field=models.ImageField(upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='profile_img',
            name='image',
            field=models.ImageField(upload_to='profile_photo/'),
        ),
    ]
